; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;在配置文件中分号开头为注释
[platformio]
;将源代码的编译目录移到项目目录下，否则默认src下
src_dir = ./
include_dir = ./

[env:genericSTM32F103C6]
;配置平台和板子
platform = ststm32
board = genericSTM32F103C6
; change microcontroller
board_build.mcu = stm32f103c6t6

; change MCU frequency
board_build.f_cpu = 72000000L
; framework = stm32cube
;编译配置-D是宏定义，-Idir是include文件目录,读者可按自己项目结构更改
build_flags =         
  -D STM32F103x6
  -ICore/Inc
  -IDrivers/CMSIS/Include
  -IDrivers/CMSIS/Device/ST/STM32F1xx/Include
  -IDrivers/STM32F1xx_HAL_Driver/Inc
  -IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy
  -Wl,-u,_printf_float,-u,_scanf_float    ; printf float 
  ; -IInc
  ; -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
  ; -IMiddlewares/Third_Party/FreeRTOS/Source/include
  ; -IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
  ; -ITask

;选择编译文件的所在路径，这里包含了源文件路径，启动文件，驱动库和rtos路径。如果+<*>便是路径下的所以文件，-<.git/>便是忽略.git路径下的文件
build_src_filter = +<Core/Src> +<startup_stm32f103x6.s> +<Drivers/> +<Middlewares/>
;选择链接文件
board_build.ldscript = ./STM32F103C6Tx_FLASH.ld
;选择下载的仿真器，这里是选择的serial，如果不设置默认stlink
; debug_tool = cmsis-dap
upload_protocol = cmsis-dap
upload_port = COM5
; platform_packages = tool-openocd@~2.1000.0
;upload_speed = 115200
;字面意思
;debug_tool = jlink
